### ISSUE TITLE
Z-order problem with right click context menu on colored options

### ISSUE THREAD

**Issue by apoapostolov** [LebombJames/combat-tracker-disposition#2]
When right-click on any combatant in the tracker, the context menu appears under the combatants rather than over them. This is only problem when using the default chat combat tracker tab. Same happens on a pulled drawer (2nd screenshot)

![image](https://user-images.githubusercontent.com/4083812/172040159-216fe764-38f6-4d52-8d82-508694f2d9fa.png)

![image](https://user-images.githubusercontent.com/4083812/172040201-bb16556a-1baa-426f-8759-9ed42328bdec.png)

**Comment by LebombJames** [comment]
Fixed in v1.1.2
