### ISSUE TITLE
V11 Compatibility?

### ISSUE THREAD

**Issue by kagedansa** [LebombJames/combat-tracker-disposition#5]
Unfortunately, the module no longer works under V11.
The following error appears in the console:

![image](https://github.com/LebombJames/combat-tracker-disposition/assets/110729103/16f16ecb-41bb-42e3-9bf6-67c6b2679d48)

**Comment by LebombJames** [comment]
I use the module in my weekly sessions on V11 and there are no issues. I suspect this is due to a token with a deleted actor or something similar. If you can figure out precisely how to reproduce this then let me know
